version: '3.5'
services:
  rabbit.producer:
    build: .
    image: streamline27/rabbit.producer:latest
    container_name: rabbit.producer
    ports:
      - "9080:9080"
    environment:
      - "spring.profiles.active=docker"
      - "RABBIT_ADDRESSES=localhost:5672"
      - "RABBIT_USERNAME=guest"
      - "RABBIT_PASSWORD=guest"
#    volumes:
#      - "/Users/Vladislav/Development/Home/Kotlin/logs:/logs"